//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demotme
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Struct_order = new HashSet<Struct_order>();
        }

        [Display(Name = "ID")]
        public int id { get; set; }
        [Display(Name = "Количество")]
        public Nullable<int> colvo { get; set; }
        [Display(Name = "Описание")]
        public string description { get; set; }
        [Display(Name = "Категория")]
        public int id_category { get; set; }
        [Display(Name = "Путь к картинке")]
        public string ImgPath { get; set; }
        [Display(Name = "Название продукта")]
        public string name_prod { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Struct_order> Struct_order { get; set; }
    }
}
